export const challenges = [
    {
        id: 1,
        title: 'Fund your wallet with ETH Testnet from the Sepolia Network',
        description: 'Go to a faucet and get some testnet ETH Sepolia. A few popular faucets are: [Google Cloud Faucet](https://cloud.google.com/application/web3/faucet/ethereum/sepolia), [Alchemy Faucet](https://www.alchemy.com/faucets/ethereum-sepolia)',
        points: 10,
        difficulty: 'Easy',
        category: 'Transactions',
    },
    {
        id: 2,
        title: 'Fund your wallet with ETH Testnet from the Holesky Network',
        description: 'Go to a faucet and get some testnet ETH Holesky. A few popular faucets are: [Google Cloud Faucet](https://cloud.google.com/application/web3/faucet/ethereum/sepolia), [Alchemy Faucet](https://www.alchemy.com/faucets/ethereum-sepolia)',
        points: 10,
        difficulty: 'Easy',
        category: 'Transactions',
    },
    {
        id: 3,
        title: 'Send a Transaction',
        description: 'Send 0.0001 ETH Sepolia to our class Ethereum wallet address (0x6836684527E29572A855fEf7348637bE8d972BB7).',
        points: 10,
        difficulty: 'Easy',
        category: 'Transactions',
    },
    {
        id: 4,
        title: 'Lend your ETH',
        description: 'Lend 0.001 ETH Sepolia using the [Aave](https://staging.aave.com/).',
        points: 20,
        difficulty: 'Medium',
        category: 'Lending',
    },
    {
        id: 5,
        title: 'Borrow USDC',
        description: 'Borrow 0.001 USDC Sepolia using the [Aave](https://staging.aave.com/). You can decide if you want to go with the Stable or Variable interest rate',
        points: 20,
        difficulty: 'Medium',
        category: 'Lending',
    },
    {
        id: 6,
        title: 'Send your USDC to friend',
        description: 'Send 0.001 USDC Sepolia to your classmate\'s Ethereum wallet address.',
        points: 10,
        difficulty: 'Easy',
        category: 'Transactions',
    },
    {
        id: 7,
        title: 'Add the Holesky Network to your Wallet',
        description: 'Follow the [instructions]([Add Holesky Network](https://revoke.cash/learn/wallets/add-network/ethereum-holesky) to add the Holesky Network to your wallet.',
        points: 25,
        difficulty: 'Medium',
        category: 'Wallet',
    },
    {
        id: 8,
        title: 'Stake your ETH',
        description: 'Use [Lido](https://testnet.fi/) to Stake 10 Holesky ETHs',
        points: 30,
        difficulty: 'Hard',
        category: 'Staking',
    },
    {
        id: 9,
        title: 'Import Token to your Wallet',
        description: 'Import the Lido Holesky token to your wallet using the contract address: 0x3F1c547b21f65e10480dE3ad8E19fAAC46C95034. Now you should see the sEth token balance you just staked',
        points: 25,
        difficulty: 'Medium',
        category: 'Wallet',
    },
    {
        id: 10,
        title: 'Unstake your ETH',
        description: 'Use [Lido](https://testnet.fi/) to Unstake 5 Holesky ETHs',
        points: 10,
        difficulty: 'Easy',
        category: 'Staking',
    },
    {
        id: 11,
        title: 'Add the Sepolia Base Network to your Wallet',
        description: 'This is similar to how you added the Holesky Network. The Network Name is Base Sepolia, RPC URL is https://sepolia.base.org, the Chain ID is 84532, and the symbol is ETH.',
        points: 25,
        difficulty: 'Medium',
        category: 'Wallet',
    },
    {
        id: 12,
        title: 'Bridge ETH for Base',
        description: 'Bridge 0.005 ETH Sepolia ETH for Sepolia Base on [Superbridge](https://testnets.superbridge.app/base-sepolia). The whole process should have 2 steps and the final step is that you will receive ETH on the Sepolia Base Network',
        difficulty: 'Hard',
        points: 30,
        category: 'Bridging',
    },
    {
        id: 13,
        title: 'Bridge ETH for Base',
        description: 'Bridge 0.005 ETH Sepolia ETH for Sepolia Base on [Superbridge](https://testnets.superbridge.app/base-sepolia). The whole process should have 2 steps and the final step is that you will receive ETH on the Sepolia Base Network',
        difficulty: 'Hard',
        points: 30,
        category: 'Bridging',
    },
];
